### ISSUE TITLE
Service 'local-dss-core-service' failed to build

### ISSUE THREAD

**Issue by erdeTH** [interuss/dss#711] opened 2022-02-14 16:10 UTC
Hello

I am currently trying to run the standalone local InterUSS instance as per the standalone_instance.md and experienced build fail on 'local-dss-core-service' as shown below.

![image](https://user-images.githubusercontent.com/99272002/153899962-afc53856-fbe7-4497-9024-e97c13bacc8c.png)

Could you advice the solution to solve this issue?
Note that I performed running run_locally.sh on the Linux that freshly installed Docker and Docker Compose without any modification in configuration.

**Comment by BenjaminPelletier** [comment] 2022-02-14 21:19
`.git` is a folder (in the root of the repository) created by git when a repository is cloned.  If you obtained the code by downloading it, then delete that folder and instead acquire the code with `git clone https://github.com/interuss/dss`.  Since it looks like you're using Ubuntu, you get get git with `sudo apt-get install git`.

**Comment by santiagodelhierro98** [comment] 2022-02-16 09:57
Hi, 

I am experiencing similar difficulties when running _run_locally.sh_ on a Windows machine using Docker. Both CrockroachDB and Dummy OAuth token are reachable, but the DSS HTTP request seems to crash (attached a screenshot). Could you advice the solution to solve this issue? Thank you in advance!
![issue when run locally](https://user-images.githubusercontent.com/59063983/154240206-5be89412-ef65-45b1-a333-19211ed23780.JPG)

**Comment by BenjaminPelletier** [comment] 2022-03-01 00:27
I'll close this for now, but please reopen if the issue is not resolved by the comment above.

**Closed by BenjaminPelletier** 2022-03-01 00:27 UTC
