### ISSUE TITLE
DSS Build Locally error

### ISSUE THREAD

**Issue by hrishiballal** [interuss/dss#629] opened 2021-11-26 10:59 UTC
**Describe the bug**
When I sync the latest repo and then try to build the DSS locally, I am getting a error in GRPC server. Attaching Docker logs: [dss_run_locally.txt](https://github.com/interuss/dss/files/7608264/dss_run_locally.txt)

**To Reproduce**
- Synced my fork to the latest upstream (https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)
- Ran `docker system prune` and `docker system prune -a`
- Then `/build/dev/run_locally.sh`

**Expected behavior**
A DSS instance should be running locally

**Screenshots**

![dss](https://user-images.githubusercontent.com/1588744/143570583-15cdbc4f-6207-46d6-9872-8e6f26c7a482.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 + WSL
 - Browser NA
 - Version : NA

**Additional context**

**Comment by BenjaminPelletier** [comment] 2021-11-26 18:00
I'm unable to reproduce this -- after `docker system prune` and `docker system prune -a` on a Mac, `run_locally.sh` works as intended.  On a Windows 11 machine with WSL, cloning this repository for the first time, `run_locally.sh` also works as intended.

The command `/build/dev/run_locally.sh` is not actually a valid command (the leading `/` indicates an absolute directory not a relative one), so could you copy the entire console output starting with the command you ran to verify what is actually happening?  And, could you run the commands `git log -n 2` and `git status` just before the `run_locally.sh` command and include that command and its output when copying the console output?

**Comment by artur-ag** [comment] 2021-12-02 05:52
I originally got this error on commit 179f3f1a50917e18e4e309fb10c0d925d4986017 and asked hrishiballal about it. I'm also using Windows 10 + WSL. At the time, I just deleted the `dss_sandbox` container through the Docker GUI, I wasn't aware of the `docker system prune -a` command. Today I tried this:
* ran `docker system prune -a`
* completely deleted my working copy of interuss/dss (`git status` didn't list any changes though)
* cloned the more recent commit fca71334b7d1fe0b61d6de319573bd8f02655af0 in a new folder
* `cd build/dev/` and `./run_locally.sh`
And now `run_locally.sh` works for me. I'm not sure if something relevant changed between those two commits, or if my local docker environment just hadn't been cleaned properly.

One thing I noticed was that I had to change git's option `core.autocrlf` to false, otherwise the `run_locally` script would be cloned with `\r\n` line endings and bash would complain about it. I cannot remember if I did this when I pulled the older commit. If I did, and then changed _only_ run_locally manually but left other files with `\r\n` endings, maybe that could've caused the error... When `core.autocrlf` is not set to false, `git status` ignores line endings.

**Comment by hrishiballal** [comment] 2021-12-04 08:59
Apologies, I have been a bit caught up and could not follow up, Yes basically, for WSL, I do a `sed -i 's/\r$//' filename` ([source](https://stackoverflow.com/questions/11616835/r-command-not-found-bashrc-bash-profile)) for all the .sh files in the `/build/dev` and `/build/dev/startup` directories if there is a issue. I need to re-check it on my side. I will do it later today.

**Comment by hrishiballal** [comment] 2021-12-04 09:00
OK I have now been able to run / bring up DSS via Windows 10 + WSL. 
1) My `docker version` and `docker compose version` is below: 
![image](https://user-images.githubusercontent.com/1588744/144594297-86a4c932-43b5-4c76-8ed2-6d38cc3d9384.png)
2) Instead of `./run_locally.sh` , I ran `docker compose -f docker-compose_dss.yaml up` 
![image](https://user-images.githubusercontent.com/1588744/144594342-bb104625-24fa-473e-adea-fca36a6a0d7f.png)
3) When you run it like this it seems to be working: 
![image](https://user-images.githubusercontent.com/1588744/144594415-dd946f6a-e1da-4d7e-8508-982331b86c69.png)
![image](https://user-images.githubusercontent.com/1588744/144594426-32e011a2-8120-4c95-8d88-6b2b7ba783b8.png)

I think this has to do with the way Windows treats the `docker-compose`, I am running it without the `-` , sharing my Docker for Windows Desktop settings:
![image](https://user-images.githubusercontent.com/1588744/144594778-3c455313-e7e3-4320-9efd-ffc7ba4ce1db.png)

**Comment by artur-ag** [comment] 2021-12-10 07:58
I think I identified the problem. If, at any point, I click on the Start button of the DSS app in Docker Desktop (GUI), then the grpc container will throw the error `Failed to create remote ID server [...] Caused by: Failed to create remote ID store [...] Caused by: Remote ID schema version check failed`. And after that, if I try to stop and restart via the GUI, or via the command line, I always get the same error. Maybe starting the DSS this way is corrupting something.

![image](https://user-images.githubusercontent.com/9512554/145537828-1a927bb8-7aac-431e-a3f7-1446ee517024.png)

If I delete the app/containers and the `dev_local-dss-data` volume, and recreate everything with `docker compose -f docker-compose_dss.yaml up`, then it works again, and I can start/stop it multiple times if I do everything from the command line. I guess I just have to avoid the Docker Desktop GUI buttons. Also, deleting and recreating only the volume is a lot faster than running `docker system prune`.

**Comment by BenjaminPelletier** [comment] 2021-12-17 17:27
This sounds like a mismatched database version; the last error string you included can be found [here](https://github.com/interuss/dss/blob/b5e347f27d5464ca261cddfd6abdefc1831b2acf/pkg/rid/store/cockroach/store.go#L75), but it should propagate an error from `CheckCurrentMajorSchemaVersion`, meaning there should be one more level of depth on that stack trace, and I'll bet the final root cause error message will be [`Unsupported schema version for [...]! Got [...], requires major version of [..]. Please check https://github.com/interuss/dss/tree/master/build#updgrading-database-schemas`](https://github.com/interuss/dss/blob/8eec5085183017cc3b9d34d8b962bdc18293da5f/pkg/rid/store/cockroach/store.go#L92).  If that's the case, the most likely cause is that you created your system with `build/dev/run_locally.sh` with an earlier version of the repo, and that initialized the Cockroach database to a particular version.  Later changes to the repo (presumably #613) added a new database version, and rev'd the code to require that new database version.  So then when you later ran the new code, it needed v3.x.x, but your old Cockroach database persisted with the v2.x.x it was originally initialized with.  If you had been able to see the whole error message, I'd hope it would be pretty clear what to do (visit that link about upgrading database schemas), but let me know if that message was somehow missing.  Since you're just doing local development, you can take (and did) take the easier way out though: removing the persistent Cockroach database volume will cause `build/dev/run_locally.sh` to recreate it next time, and the newest codebase (since #613) will create a v3.x.x database rather than your old v2.x.x.  If this happens in the future, the cleanest way to delete the persistent Cockroach data is simply `build/dev/run_locally.sh down`.  The `down` docker-compose command dismantles all parts of the system, including deleting the persistent data store.  Just killing the system does not remove the persistent volumes.

If you can find a way to make this issue more obvious or more easily-resolvable by other people who have the same problem in the future, a PR or concrete/specific suggestion would be welcome.

**Comment by BenjaminPelletier** [comment] 2022-01-05 19:31
Closing for now; feel free to reopen if this issue becomes relevant again.

**Closed by BenjaminPelletier** 2022-01-05 19:31 UTC
